spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xm2?serverTimezone=GMT%2B8
#    url: jdbc:mysql://8.136.185.236:3306/xm2?serverTimezone=GMT%2B8
    username: root
    password: 123.com
  mail:
    default-encoding: utf-8
    # 主机地址
    host: smtp.qq.com
    # 邮箱名
    username: 1478588530@qq.com
    # 授权码（不是密码）
    password: nelddoxpaylsbagc
    #端口号
    port: 587
  #没拦截器url访问本地资源地址
  #url访问本地资源地址
  mvc:
    static-path-pattern: /image/**
#    view:
#      prefix: /
#      suffix: .html
  #本地资源真实存放地址
  resources:
      #阿里云
#    static-locations: file:C://JAVA/img/
      #本地
#    static-locations: file:E://JAVA/img/
      #腾讯云
    static-locations: file:/JAVA/img/
  servlet:
    multipart:
      max-file-size: 5MB
server:
  port: 80
#全局变量
information:
  #壁纸存放地址
#阿里云
#  wallpaperDisk: C:\JAVA\img\
#本地
#  wallpaperDisk: E:\JAVA\img\
#腾讯云
  wallpaperDisk: /JAVA/img/


